remote_theme: broccolini/athena
title: A Stastic test to admin a jekyll site
description: 'Admin your Jekyll sites on Github pages with Stastic '
github_repo: athena
github_username: broccolini
social_link: twitter
social_username: broccolini
theme_color: light
baseurl: /boorish_miller
